services:
  nexus_service:
    container_name: nexus_service
    image: sonatype/nexus3
    expose:
      - 8081
      - 8082
      - 8083
    ports:
      - "8082:8082"
      - "8083:8083"
      - "8081:8081"
    volumes:
      - nexus_data:/nexus-data
    restart: always

volumes:
  nexus_data:
