networks:
  monitoring:
    name: monitoring
    driver: bridge

services:
  grafana:
    container_name: grafana_service
    image: grafana/grafana-enterprise:latest
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
    ports:
      - "3000:3000"
    networks:
      - monitoring
    volumes:
      - grafana_data:/var/lib/grafana

  prometheus:
    container_name: prometheus_service
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    networks:
      - monitoring
    volumes:
      - ./conf/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

  loki:
    image: grafana/loki:latest
    container_name: loki_service
    ports:
      - "3100:3100"
    networks:
      - monitoring
    volumes:
      - ./conf/loki/loki-config.yaml:/etc/loki/config.yml
    command: -config.file=/etc/loki/config.yml

  promtail:
    image: grafana/promtail:latest
    container_name: promtail_service
    networks:
      - monitoring
    volumes:
      - ./conf/promtail/promtail-config.yaml:/etc/promtail/config.yml
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/config.yml

volumes:
  grafana_data:
  prometheus_data:
