services:
  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
      - "./rules.yml:/etc/prometheus/rules.yml"
    networks:
      - epitech_localprom
    ports:
      - 9090:9090
    depends_on:
      - loki

  node-exporter:
    image: prom/node-exporter
    networks:
      - epitech_localprom
    ports:
      - 9100:9100
    
  alert-manager:
    image: prom/alertmanager
    volumes:
      - "./alertmanager.yml:/alertmanager/alertmanager.yml"
    networks:
      - epitech_localprom
    ports:
      - 9093:9093
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-conf:/etc/grafana
    networks:
      - epitech_localprom

  loki:
    image: grafana/loki
    ports:
      - 3100:3100
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yml
    networks:
      - epitech_localprom

  promtail:
    image: grafana/promtail
    volumes:
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - epitech_localprom

  uptime-kuma:
    image: kumahq/kuma-demo
    restart: always
    ports:
      - 5001:5000
    volumes:
      - ./data:/app/data
    container_name: uptimekuma
    

volumes:
  grafana-data:
  grafana-conf:

networks:
  epitech_localprom: