apiVersion: 1

datasources:
  - name: prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus-service:9090
    isDefault: true
  - name: loki
    type: loki
    uid: loki
    access: proxy
    orgId: 1
    url: http://loki-service:3100
    isDefault: false
