apiVersion: v1
kind: Service
metadata:
  name: artisan-backend
  namespace: artisan
spec:
  type: NodePort
  selector:
    app: artisan-backend
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30009
